### ISSUE TITLE
能否增加个需求，指定指纹库文件路径

### ISSUE THREAD

**Issue by Shea-Des** [0x727/ObserverWard#133]
原因：
 observerward 和 web_fingerprint_v3.json 在同一目录下但扫描时未能找到指纹库
![image](https://user-images.githubusercontent.com/69289278/227419372-5398f78b-5e56-4e41-90a5-357238eeebf2.png)

![image](https://user-images.githubusercontent.com/69289278/227418805-ab3cbaec-8791-4ba0-a2ac-ade536e2bacc.png)

**Comment by cn-kali-team** [comment]
可，等下更新

**Comment by cn-kali-team** [comment]
不对，我在本地可以读到当前目录的指纹库啊，我看到你是用python调的，可以看看你的代码吗？我觉得你python执行observerward的时候没有设置运行目录

**Comment by Shea-Des** [comment]
我看了下，是我没有更改运行目录，是通过绝对路径来运行 observerward，在当前目录下没有找到指纹库

**Comment by cn-kali-team** [comment]
你试试在python调用observerward的时候设置cwd参数为observerward这个目录

**Comment by cn-kali-team** [comment]
```python
import subprocess
output = subprocess.Popen(['/home/kali-team/observer_ward_amd64','-t','https://httpbin.org'], cwd='/home/kali-team/')
print(output)
```

**Comment by cn-kali-team** [comment]
其他调用命令行同理，设置`cwd`参数就可以了

**Comment by Shea-Des** [comment]
感谢，已经可以了正常读到指纹库了
![image](https://user-images.githubusercontent.com/69289278/227436627-6775b1ae-79d7-42e3-b584-d913ae880104.png)
