### ISSUE TITLE
建议直接使用-tags调用nuclei模板

### ISSUE THREAD

**Issue by j4vaovo** [0x727/ObserverWard#143]
nuclei.exe -t c:\all-templates\ -tags "cisco" -es "info"

靠FingerprintHub/plugins的话 一些官方仓库没有的模板没法调用啊
感谢大佬！！

**Comment by cn-kali-team** [comment]
这两个星期有点忙，我加一个参数让你指定nuclei官方的template路径，然后我在调用nuclei的时候加上这个路径，和将指纹作为tag标签

**Comment by cn-kali-team** [comment]
但是我发现指定了tags会将我这边的tamplate部分忽略掉啊，不能指定多个路径并且加tags

**Comment by cn-kali-team** [comment]
除非不用我的这边的FingerprintHub，直接使用tags.yaml里面的标签列表去选择template

**Comment by cn-kali-team** [comment]
更新了，可以使用`--path`指定nuclei官方的templates，没什么问题可以关闭issues
