### ISSUE TITLE
批量识别会漏掉大量结果,加个超时重试选项可能好点

### ISSUE THREAD

**Issue by j4vaovo** [0x727/ObserverWard#153]
<img width="142" alt="搜狗高速浏览器截图20230524064710" src="https://github.com/0x727/ObserverWard/assets/128683738/66b4dc00-2029-4f2e-b5a5-f8715721810f">

单独把网址复制出来 -t  是能识别出来的。。。

**Comment by cn-kali-team** [comment]
我这边也遇到过，扫到Web防火墙了

**Comment by cn-kali-team** [comment]
Caused by:
    0: connection error: Connection reset by peer (os error 104)
    1: Connection reset by peer (os error 104)

**Comment by cn-kali-team** [comment]
经过测试应该是拦截了
```
  headers.insert(
      header::COOKIE,
      HeaderValue::from_static("rememberMe=admin;rememberMe-K=admin"),
  );
```
- 在考虑要不要删除掉，或者加一个开关

**Comment by j4vaovo** [comment]
没有WAF也会出现这种情况
使用200线程以上就会出现大量状态码=0的, 实际可以访问
163.com.webs 都是探测过http存活的url
<img width="791" alt="ob" src="https://github.com/0x727/ObserverWard/assets/128683738/38ee2fc7-2a3d-4939-bc1a-4d39c2c080b0">
[163.com.zip](https://github.com/0x727/ObserverWard/files/11550132/163.com.zip)

**Comment by cn-kali-team** [comment]
线程这么大加重试也没有用
