### ISSUE TITLE
指纹识别不完整

### ISSUE THREAD

**Issue by Shea-Des** [0x727/ObserverWard#165]
指纹识别不完整，例如 dahua 的指纹
+ 规则
![image](https://github.com/0x727/ObserverWard/assets/69289278/ba386a14-6871-4eab-b690-727e73dde96c)
+ 目标
![image](https://github.com/0x727/ObserverWard/assets/69289278/442b5741-54d5-4578-be69-b96a213ff667)
+ 识别结果
![image](https://github.com/0x727/ObserverWard/assets/69289278/43b2f380-a6be-4a18-bded-b8299851649a)

**Comment by cn-kali-team** [comment]
找到原因了，是没跳转过去，等下和其他问题一起更新上去

**Comment by cn-kali-team** [comment]
更新了

**Comment by Shea-Des** [comment]
ok了，测试正常
