### ISSUE TITLE
导出csv乱码

### ISSUE THREAD

**Issue by mrr-yao** [0x727/ObserverWard#169]
大佬请问这个导出csv格式乱码怎么解决啊

![1687224992845](https://github.com/0x727/ObserverWard/assets/78681164/2ad426b8-c7aa-4daa-b466-429e186fecab)

**Comment by cn-kali-team** [comment]
![image](https://github.com/0x727/ObserverWard/assets/30642514/6afdc3f7-ae5d-41ce-ae3a-de5a1453f1fb)

**Comment by mrr-yao** [comment]
感谢
