### ISSUE TITLE
当favicon.ico没有获取到时，会多次获取ico

### ISSUE THREAD

**Issue by sv3nbeast** [0x727/ObserverWard#183]
当favicon.ico没有获取到时，会多次获取ico  导致识别速度等比下降

<img width="91" alt="image" src="https://github.com/0x727/ObserverWard/assets/55974091/aafaca61-09db-4503-9feb-56d76164c20a">

**Comment by sv3nbeast** [comment]
也可能是指纹是需要请求特定路径时，需要额外请求一次ico

**Comment by cn-kali-team** [comment]
你这个favicon的响应是图片类型的吗？

**Comment by sv3nbeast** [comment]
<img width="854" alt="image" src="https://github.com/0x727/ObserverWard/assets/55974091/31df1956-e32b-400c-8a70-2ecfff5f61e9">

**Comment by sv3nbeast** [comment]
<img width="646" alt="image" src="https://github.com/0x727/ObserverWard/assets/55974091/211436d5-cb49-4c2a-bb4d-62f145b87568">

**Comment by cn-kali-team** [comment]
更新了
