### ISSUE TITLE
window版本扫描时一直报错

### ISSUE THREAD

**Issue by kk1270** [0x727/ObserverWard#186]
准备扫描七千个目标，扫描到一半时经常出现报错信息，但是还是可以接着正常扫描，运行时间久了就无法正常扫描全是报错信息了，翻了一翻终端翻到顶部全是报错信息，我用的参数是-f -c --path,以下是部分报错信息
goroutine 1178 [IO wait]:
runtime.gopark(0x2ea7e5c, 0x2e27ebc4, 0x2, 0x1b, 0x5)
        runtime/proc.go:381 +0xff fp=0x10737a70 sp=0x10737a5c pc=0xf0d70f
runtime.netpollblock(0x2e27ebb8, 0x72, 0x0)
        runtime/netpoll.go:527 +0xea fp=0x10737a88 sp=0x10737a70 pc=0xf040da
internal/poll.runtime_pollWait(0x2e27ebb8, 0x72)
        runtime/netpoll.go:306 +0x52 fp=0x10737a9c sp=0x10737a88 pc=0xf389f2
internal/poll.(*pollDesc).wait(0x1103b2d4, 0x72, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x37 fp=0x10737ab0 sp=0x10737a9c pc=0xfd82a7
internal/poll.execIO(0x1103b1f4, 0x2ea7838)
        internal/poll/fd_windows.go:175 +0x11e fp=0x10737af4 sp=0x10737ab0 pc=0xfd942e
internal/poll.(*FD).Read(0x1103b1e0, {0xf7e6000, 0x1300, 0x1300})
        internal/poll/fd_windows.go:436 +0x13b fp=0x10737b44 sp=0x10737af4 pc=0xfda01b
net.(*netFD).Read(0x1103b1e0, {0xf7e6000, 0x1300, 0x1300})
        net/fd_posix.go:55 +0x3f fp=0x10737b70 sp=0x10737b44 pc=0x110f1bf
net.(*conn).Read(0xdd7ade8, {0xf7e6000, 0x1300, 0x1300})
        net/net.go:183 +0x4f fp=0x10737ba0 sp=0x10737b70 pc=0x1124f4f
net.(*TCPConn).Read(0xdd7ade8, {0xf7e6000, 0x1300, 0x1300})
        <autogenerated>:1 +0x42 fp=0x10737bc0 sp=0x10737ba0 pc=0x1137bc2
crypto/tls.(*atLeastReader).Read(0xdd46b90, {0xf7e6000, 0x1300, 0x1300})
        crypto/tls/conn.go:788 +0x63 fp=0x10737bf8 sp=0x10737bc0 pc=0x1168e43
bytes.(*Buffer).ReadFrom(0xf49db78, {0x32a4b24, 0xdd46b90})
        bytes/buffer.go:202 +0x93 fp=0x10737c3c sp=0x10737bf8 pc=0xf54603
crypto/tls.(*Conn).readFromUntil(0xf49da00, {0x32a7a68, 0xdd7ade8}, 0x5)
        crypto/tls/conn.go:810 +0xdd fp=0x10737c64 sp=0x10737c3c pc=0x116906d
crypto/tls.(*Conn).readRecordOrCCS(0xf49da00, 0x0)
        crypto/tls/conn.go:617 +0x126 fp=0x10737de4 sp=0x10737c64 pc=0x1166616
crypto/tls.(*Conn).readRecord(...)
        crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xf49da00, {0xf5ce000, 0x1000, 0x1000})
        crypto/tls/conn.go:1316 +0x147 fp=0x10737e1c sp=0x10737de4 pc=0x116bce7
net/http.(*persistConn).Read(0x10545f40, {0xf5ce000, 0x1000, 0x1000})
        net/http/transport.go:1943 +0x141 fp=0x10737e50 sp=0x10737e1c pc=0x123a971
bufio.(*Reader).fill(0x10aa6ea0)
        bufio/bufio.go:106 +0xe9 fp=0x10737e74 sp=0x10737e50 pc=0xf61079
bufio.(*Reader).Peek(0x10aa6ea0, 0x1)
        bufio/bufio.go:144 +0x6d fp=0x10737e80 sp=0x10737e74 pc=0xf611bd
net/http.(*persistConn).readLoop(0x10545f40)
        net/http/transport.go:2107 +0x1df fp=0x10737fe8 sp=0x10737e80 pc=0x123b44f
net/http.(*Transport).dialConn.func5()
        net/http/transport.go:1765 +0x27 fp=0x10737ff0 sp=0x10737fe8 pc=0x1239fe7
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0x10737ff4 sp=0x10737ff0 pc=0xf3d881
created by net/http.(*Transport).dialConn
        net/http/transport.go:1765 +0x1480

goroutine 1343 [select]:
runtime.gopark(0x2ea7ea8, 0x0, 0x9, 0x18, 0x1)
        runtime/proc.go:381 +0xff fp=0x10d53e80 sp=0x10d53e6c pc=0xf0d70f
runtime.selectgo(0x10d53fd0, 0x10d53f9c, 0x0, 0x0, 0x2, 0x1)
        runtime/select.go:327 +0xbc0 fp=0x10d53f70 sp=0x10d53e80 pc=0xf1e040
net/http.(*persistConn).writeLoop(0xf6595e0)
        net/http/transport.go:2410 +0xde fp=0x10d53fe8 sp=0x10d53f70 pc=0x123cece
net/http.(*Transport).dialConn.func6()
        net/http/transport.go:1766 +0x27 fp=0x10d53ff0 sp=0x10d53fe8 pc=0x1239fa7
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0x10d53ff4 sp=0x10d53ff0 pc=0xf3d881
created by net/http.(*Transport).dialConn
        net/http/transport.go:1766 +0x14d9

goroutine 1377 [select]:
runtime.gopark(0x2ea7ea8, 0x0, 0x9, 0x18, 0x1)
        runtime/proc.go:381 +0xff fp=0x1079bea4 sp=0x1079be90 pc=0xf0d70f
runtime.selectgo(0x1079bfc8, 0x1079bfb8, 0x0, 0x0, 0x2, 0x1)
        runtime/select.go:327 +0xbc0 fp=0x1079bf94 sp=0x1079bea4 pc=0xf1e040
net.(*netFD).connect.func2()
        net/fd_windows.go:95 +0x96 fp=0x1079bff0 sp=0x1079bf94 pc=0x1110bb6
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0x1079bff4 sp=0x1079bff0 pc=0xf3d881
created by net.(*netFD).connect
        net/fd_windows.go:94 +0x3b9

**Comment by kk1270** [comment]
使用的nuclei模板是plugins文件夹

**Comment by cn-kali-team** [comment]
很明显这是go语言的报错，并不是我的程序的
