### ISSUE TITLE
mac下运行异常,使用brew安装的工具

### ISSUE THREAD

**Issue by 1nformation** [0x727/ObserverWard#200]
<img width="1002" alt="image" src="https://github.com/0x727/ObserverWard/assets/93757156/c42cd735-d7ec-44e8-b001-29c8dcd2d715">

**Comment by 1nformation** [comment]
<img width="1002" alt="image" src="https://github.com/0x727/ObserverWard/assets/93757156/0246fc9c-851d-4d1c-b02f-4ceffa6220c8">

**Comment by cn-kali-team** [comment]
--update-plugins

**Comment by 1nformation** [comment]
> --update-plugins

<img width="1002" alt="image" src="https://github.com/0x727/ObserverWard/assets/93757156/cdd5a8bf-e4ac-404f-8fff-53d3d90104b8">

**Comment by cn-kali-team** [comment]
再执行一次，-u参数
网络不好可以手动下载[指纹库](https://0x727.github.io/FingerprintHub/web_fingerprint_v3.json)到你的`/Users/Alice/Library/Application Support/observer_ward/web_fingerprint_v3.json`

**Comment by 1nformation** [comment]
> 再执行一次，-u参数 网络不好可以手动下载[指纹库](https://0x727.github.io/FingerprintHub/web_fingerprint_v3.json)到你的`/Users/Alice/Library/Application Support/observer_ward/web_fingerprint_v3.json`

执行 -u 也是这个提示信息

**Comment by 1nformation** [comment]
我手动下载指纹库

**Comment by cn-kali-team** [comment]
当前文件夹下有web_fingerprint_v3.json文件吗，如果有就删除掉

**Comment by 1nformation** [comment]
> /Users/Alice/Library/Application Support/observer_ward/web_fingerprint_v3.json

我替换了这个文件,按照你给的链接下载了新的,不报错了可以跑了.谢谢师傅了
