### ISSUE TITLE
生成不了自定义指纹的json文件

### ISSUE THREAD

**Issue by prohk** [0x727/ObserverWard#205]
<img width="802" alt="image" src="https://github.com/0x727/ObserverWard/assets/37725167/d1cf7754-d048-42ce-bd09-182fac8f7a71">

**Comment by cn-kali-team** [comment]
--yaml指定的是json目录

**Comment by cn-kali-team** [comment]
图片下面不是提示miss field name吗，检查一下yaml的格式
