### ISSUE TITLE
The fingerprint library cannot be found in the current directory!

### ISSUE THREAD

**Issue by xxsmile123** [0x727/ObserverWard#21]
问题版本：observer_ward 2022.3.15
系统版本：10.0.19042 暂缺 Build 19042——Microsoft Windows 10 企业版
问题具体内容：

工具解压路径为：D:\security_tools\Information_Gathering\finger_about\observer_ward
更新插件时，默认路径为：C:\Users\mimikatz\AppData\Roaming\observer_ward\plugins.zip
在D:\security_tools\Information_Gathering\finger_about\observer_ward\下，会出现以下报错，且无法指纹识别：
D:\security_tools\Information_Gathering\finger_about\observer_ward>observer_ward.exe -t https://httpbin.org
 __     __     ______     ______     _____
/\ \  _ \ \   /\  __ \   /\  == \   /\  __-.
\ \ \/ ".\ \  \ \  __ \  \ \  __<   \ \ \/\ \
 \ \__/".~\_\  \ \_\ \_\  \ \_\ \_\  \ \____-
  \/_/   \/_/   \/_/\/_/   \/_/ /_/   \/____/
Community based web fingerprint analysis tool.
_____________________________________________
:  https://github.com/0x727/FingerprintHub  :
:  https://github.com/0x727/ObserverWard    :
 --------------------------------------------
The fingerprint library cannot be found in the current directory!
Update fingerprint library with `-u` parameter!
[ https://httpbin.org | [] | 9593 | 200 | httpbin.org ]
Important technology:

+---------------------+------+--------+-------------+-------------+----------+
| url                 | name | length | status_code | title       | priority |
+=====================+======+========+=============+=============+==========+
| https://httpbin.org |      | 9593   | 200         | httpbin.org | 2        |
+---------------------+------+--------+-------------+-------------+----------+

在C:\Users\mimikatz\AppData\Roaming\observer_ward下时，则可以正常使用。如下图所示：
C:\Users\mimikatz\AppData\Roaming\observer_ward>observer_ward.exe -t https://httpbin.org
 __     __     ______     ______     _____
/\ \  _ \ \   /\  __ \   /\  == \   /\  __-.
\ \ \/ ".\ \  \ \  __ \  \ \  __<   \ \ \/\ \
 \ \__/".~\_\  \ \_\ \_\  \ \_\ \_\  \ \____-
  \/_/   \/_/   \/_/\/_/   \/_/ /_/   \/____/
Community based web fingerprint analysis tool.
_____________________________________________
:  https://github.com/0x727/FingerprintHub  :
:  https://github.com/0x727/ObserverWard    :
 --------------------------------------------
[ https://httpbin.org |["swagger"] | 9593 | 200 | httpbin.org ]
Important technology:

+---------------------+---------+--------+-------------+-------------+----------+
| url                 | name    | length | status_code | title       | priority |
+=====================+=========+========+=============+=============+==========+
| https://httpbin.org | swagger | 9593   | 200         | httpbin.org | 5        |
+---------------------+---------+--------+-------------+-------------+----------+

问题诉求：请问工具是否不可指定路径存放呢。

**Comment by cn-kali-team** [comment]
如果程序的当前目录有指纹库会优先使用当前目录的，当前目录没有就用.config/observer_ward目录的

**Comment by xxsmile123** [comment]
问题解决了
