### ISSUE TITLE
功能建议: 增加路径后的指纹识别

### ISSUE THREAD

**Issue by sv3nbeast** [0x727/ObserverWard#213]
有一些站点需要加入特定目录才能访问到，但是将目录传入工具后，比如
http://xx.xxx.com/api/
工具会自动把/api去除后去进行指纹识别

感谢提供的工具

**Comment by cn-kali-team** [comment]
不会啊，不然我docker的指纹/version是怎么识别到的

**Comment by sv3nbeast** [comment]
我这里遇到的描述一下哈

当加入/api/后      一些被动指纹是可以识别出来的，比如返回体中存在123456为 A指纹  这些可以判断

以帆软为例
有一些网站不是默认回显的，需要访问帆软路径才能识别到  /webroot/decision/login

当我加入二级目录后/api      工具是不会访问 /api/webroot/decision/login的 导致无法识别

也不会访问二级目录/api/后的favicon.ico  

<img width="1135" alt="image" src="https://github.com/0x727/ObserverWard/assets/55974091/08813cf7-20a6-49be-88b9-249a419e8594">

**Comment by cn-kali-team** [comment]
https://github.com/0x727/ObserverWard/actions/runs/7028964315
更新了，favicon就不考虑拼接了，浏览器也只会请求首页的
