### ISSUE TITLE
302跳转类站点检测异常

### ISSUE THREAD

**Issue by zeroChen00** [0x727/ObserverWard#220]
示例：http://x.com:80访问会跳转hhttps://x.com或https://b.com的身份认证平台（均为一层跳转）
问题如下：
1、扫描http://x.com:80返回结果为200响应码的https://x.com:80（不带端口结果显示也为https），而不是302的跳转http://x.com的结果
在字写脚本引入ObserverWard时，http://x.com无法匹配到https://x.com，会导致脚本认为http://x.com失活，存在大量误报

**Comment by cn-kali-team** [comment]
不懂，请描述清楚点

**Comment by zeroChen00** [comment]
![Snipaste_2023-12-27_15-39-34](https://github.com/0x727/ObserverWard/assets/85620191/2553a7fc-874d-4362-a5f9-180e3cb65514)
简单来说就是扫描一个http的站，结果变成为https了。（不论该站点302跳转后为http还是https，输出结果均为https）

**Comment by cn-kali-team** [comment]
那肯定是网站自己跳的是https啊
observer_ward -t http://target:80 --verify a
自己看跳转过程

**Comment by cn-kali-team** [comment]
你是认为跳转后的端口不应该为80？

**Comment by zeroChen00** [comment]
> 你是认为跳转后的端口不应该为80？

对的，
1、如果是本站http跳转https，结果应该为https://x.com或者https://x.com:443，而不是80
2、还有个跳转第三方身份验证的情况，结果应该是http://x.com，响应值为302；而不是https://x.com:80，响应值200

**Comment by cn-kali-team** [comment]
更新了

**Comment by zeroChen00** [comment]
师傅牛逼
