### ISSUE TITLE
v2023.12.29 版本依旧存在响应码0

### ISSUE THREAD

**Issue by zeroChen00** [0x727/ObserverWard#235]
如题，0响应码网站重新跑一遍，部分为200，部分依旧为0。为0的连接访问后，以下三种情形均有：同源跳转、非同源跳转、无法访问

**Comment by cn-kali-team** [comment]
有目标吗？不方便发GitHub可以加我微信

**Comment by zeroChen00** [comment]
> 有目标吗？不方便发GitHub可以加我微信

可以的，微信？

**Comment by cn-kali-team** [comment]
Kali-Team
