### ISSUE TITLE
指纹格式报错

### ISSUE THREAD

**Issue by Shea-Des** [0x727/ObserverWard#240]
![image](https://github.com/0x727/ObserverWard/assets/69289278/3310c311-cc94-4ded-93f1-696015a5ba9a)

下载历史正常运行

https://raw.githubusercontent.com/0x727/FingerprintHub/dc3b90a4239c336886cc8e3e15804750ebed2089/web_fingerprint_v3.json

**Comment by cn-kali-team** [comment]
我看看是不是今天早上有个人提交了新指纹有问题

**Comment by cn-kali-team** [comment]
https://github.com/0x727/FingerprintHub/issues/187
的keyword没填，现在更新了，删除指纹重新-u更新一下就好了

**Comment by Shea-Des** [comment]
可以了
