### ISSUE TITLE
能不能在nuclei模板目录新增一个默认扫描的目录

### ISSUE THREAD

**Issue by tgllsy** [0x727/ObserverWard#242]
nuclei-templates目录下的模板根据指纹匹配，但有时需要一些脚本对全部资产都要扫描到，无论是否匹配到指纹。比如扫备份文件、.git 、svn 等。能否在nuclei-templates设置一个default 目录。其目录下的文件会被所有目标调用。

**Comment by cn-kali-team** [comment]
可以

**Comment by cn-kali-team** [comment]
https://github.com/0x727/ObserverWard/releases/tag/v2024.1.22
