### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by sv3nbeast** [0x727/ObserverWard#243]
比如指纹设置
  {
    "path": "/1/2/#file?a=a",
    "request_method": "get",
    "request_headers": {},
    "request_data": "",
    "status_code": 0,
    "headers": {},
    "keyword": [
      ""
    ],
    "favicon_hash": [],
    "priority": 3,
    "name": ""
  },
  
  这样在burp中查看请求的路径会变成/1/2/%23file%3Fa=a

**Comment by cn-kali-team** [comment]
这个#在客户端是没有意义的，只有在浏览器才有用，可以去学习一下URL的组成
