### ISSUE TITLE
无法识别

### ISSUE THREAD

**Issue by ic3s3137** [0x727/ObserverWard#257]
host为ip的url文件，当url条目为73个时可以正常识别，当url条目为142个时一瞬间返回全部结果为全空，--stdin和-f都一样的效果。
![WX20240228-163132@2x](https://github.com/0x727/ObserverWard/assets/52555043/dc4937f1-66b1-46b5-a67d-acad21f4ee29)

**Comment by cn-kali-team** [comment]
检查文件的编码，和每个目标的开头结尾是否有不可见字符
