### ISSUE TITLE
调用afrog无结果

### ISSUE THREAD

**Issue by ahisec** [0x727/ObserverWard#270]
![image](https://github.com/0x727/ObserverWard/assets/3255339/974458e0-a449-4cc3-9c2d-405474eb0975)
afrog进程是在运行
![image](https://github.com/0x727/ObserverWard/assets/3255339/20d40243-b280-448f-98dc-ae7a9613d367)
单独运行命令能识别出漏洞
![image](https://github.com/0x727/ObserverWard/assets/3255339/5209324e-49fc-4224-a988-1c26be8bed4c)

**Comment by ahisec** [comment]
afrog Version 3.0.2

**Comment by cn-kali-team** [comment]
我看看是不是json结果解析出问题了

**Comment by cn-kali-team** [comment]
有些结果缺少了`infodescription`字段所以解析失败了，稍后更新，等这跑完了再更新一下 https://github.com/0x727/ObserverWard/actions/runs/8388173659
