### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.10/src/into_url.rs:70:14 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by linluhaijing** [0x727/ObserverWard#36]
thread 'tokio-runtime-worker' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.10/src/into_url.rs:70:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace       这种是啥错误呀

**Comment by cn-kali-team** [comment]
目标的URL有问题？

**Comment by linluhaijing** [comment]
我之前也是这样放的目标 但是没这种问题

**Comment by cn-kali-team** [comment]
方便发一下目标吗？我复现一下，可能在拼接URL的时候出问题了。
私发我微信也行: Kali-Team
