### ISSUE TITLE
6.1 版本的macos intel报错

### ISSUE THREAD

**Issue by ThestaRY7** [0x727/ObserverWard#44]
observer_ward_v2022.6.1_x86_64-apple-darwin

报错内容：
thread 'main' panicked at 'BAD JSON: Error("EOF while parsing a value", line: 1, column: 0)', src/lib.rs:293:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    30088 abort      ./observer_ward

**Comment by cn-kali-team** [comment]
指纹文件没问题吗？

**Comment by ThestaRY7** [comment]
请问怎么删除旧的指纹文件呢？我只是--update更新了指纹文件

**Comment by ThestaRY7** [comment]
解决了，谢谢
