### ISSUE TITLE
ObserverWard指纹识别问题

### ISSUE THREAD

**Issue by helloyw** [0x727/ObserverWard#48]
师傅ObserverWard当指纹库编写成通过url访问来进行指纹识别，会遇到一些网站默认404页面也是状态200，导致识别出现误报率较高的问题。

**Comment by cn-kali-team** [comment]
但是一般人写规则都不喜欢填状态码，这是字段属于历史遗留问题，本来是想删除的，但是某些地方又要用到。很多指纹的状态码都是0的，问题不大。

**Comment by helloyw** [comment]
有些指纹没办法根据页面特征来进行识别，只能通过主动发起对应的存在的url来进行识别就会存在这个问题所以还是希望能够解决一下这个问题。

**Comment by cn-kali-team** [comment]
这个功能已经有了啊，path填写你想请求的路径就行了，我记得指纹库里有path不是／的指纹。

**Comment by helloyw** [comment]
是有，但是就会出现我提issus的问题，有些站404页面返回的也是200，导致出现误报较高

**Comment by cn-kali-team** [comment]
我觉得只要关键词的指纹规则足够强，这状态码可以忽略不识别，比如thinkphp的任意404页面都是返回状态码200，但是这个页面有关键词：十年磨一剑，thinkphp，就可以识别到thinkphp，和状态码没有关系。
第一版指纹规则是有固定请求一个不存在的路径，也就是404页面的特征识别，但是这种很少见，而且首页也能识别到，就把这个功能删除了。

**Comment by helloyw** [comment]
好的谢谢师傅
