### ISSUE TITLE
macos下添加nuclei环境变量无效

### ISSUE THREAD

**Issue by 80264666** [0x727/ObserverWard#74]
修改的 .zshrc  文件 添加了 alias nuclei="~/nuclei"

在/Users/xxxx/Desktop/tools/observer_ward/目录 运行nuclei正常

但是

➜  observer_ward ./observer_ward --plugins default
Please install nuclei to the environment variable!
➜  observer_ward

**Comment by cn-kali-team** [comment]
这个是shell命令行解释器做的事情，我的程序没有办法回去到你的别名配置，如果要支持别名我需要读$SHELL环境变量判断你是不是用了bash还是zsh或者其他的shell命令行解析器，再加载你的profile文件，各个shell的profile配置文件都不一样，所以我不会添加这个支持。

建议新建一个文件夹放你的工具，然后把这个文件夹加入PATH环境变量里面，或者直接使用go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest 安装nuclei。
