### ISSUE TITLE
顺便提个小想法：增加nuclei的payload输出

### ISSUE THREAD

**Issue by dark5net** [0x727/ObserverWard#95]
首先非常非常感谢0x727团队的大佬们能开源这款这么优秀的工具！

最近想大批量检测站点，直接通过obseverward调用nuclei确实非常方便，但是结果的处理个人感觉不是很方便，在入库的时候发现是没有payload的，在以后的工作中还需要重新根据plugins选项去查找payload测试。

如果大佬有时间的话，可以考虑看看增加对调用nuclei扫描结果的输出。

**Comment by cn-kali-team** [comment]
保存到json文件可以做，我加个开关吧

**Comment by cn-kali-team** [comment]
更新了，等ci跑完就可以下载了

**Comment by cn-kali-team** [comment]
将nuclei的请求和响应的payload保存到json结果--irr

➜  ~ ./observer_ward_amd64 -f target.txt --json result.json --plugins default --irr
